Jellyfin template
linuxserver/docker-templates pull request #149
Opened 2019-06-09 23:55 UTC by CHBMB

Needs support thread, testing and container to go live

2019-06-10 21:26 UTC, tobbenb requested changes
Same changes as for plex. Should be `--device=/dev/dri` in the text.

2019-06-10 23:01 UTC, CHBMB commented
@tobbenb Try now.

2019-06-11 07:34 UTC, tobbenb approved these changes

2019-06-11 07:36 UTC, tobbenb approved these changes

2019-06-11 09:41 UTC, merged